spring:
  jackson:  
    parser:
      allow-backslash-escaping-any-character: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: alex
    password: Magic_nava02
    driverClassName: oracle.jdbc.driver.OracleDriver
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: testossot@gmail.com
    password: vztyucugdlyiudaf
jpa:
  show-sql: true
  open-in-view: false
  hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Oracle10gDialect
